# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'text' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'Masonry', '0.5.3'
pod 'SDWebImage', '~> 4.1.0'
pod 'SDWebImage/GIF'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.10'

end
